name: backend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run build
    
      - uses: actions/download-artifact@v4
        with:
          name: coverage
          path: backend/covergate/**
      - uses: actions/download-artifact@v4
        with:
          name: coverage
          path: backend/cdist/index.js
